package locales

// ============================================================================
// Strings extracted from internal/bot/handlers/dashboard/*.go
// (HTTP handlers for the «Мой профиль» dashboard Mini App).
// Generated by the string-extraction pass; keep user-facing copy here.
// ============================================================================

// Log messages emitted by the dashboard HTTP handlers.
const (
	LogDashboardMetricsDemo    = "[DASHBOARD] /api/metrics (DEMO) отданы синтетические метрики"
	LogDashboardMetrics        = "[DASHBOARD] /api/metrics отданы для user=%d (noData=%v)"
	LogDashboardReportsDemo    = "[DASHBOARD] /api/reports (DEMO) отданы синтетические отчёты"
	LogDashboardDemoPDFUnavail = "[DASHBOARD] PDF недоступен для демо-отчёта (%v) - отдаю HTML"
	LogDashboardDemoPDFSent    = "[DASHBOARD] демо PDF-отчёт отдан: %d байт"
	LogDashboardReportHTMLErr  = "[DASHBOARD] не удалось получить HTML отчёта id=%d: %v"
	LogDashboardPDFConvUnavail = "[DASHBOARD] PDF-конвертация недоступна для отчёта id=%d: %v - отдаю HTML"
	LogDashboardPDFSent        = "[DASHBOARD] PDF-отчёт id=%d отдан пользователю (user=%d): %d байт"
	LogDashboardProfileSaveErr = "[DASHBOARD] не удалось сохранить профиль user=%d: %v"
	LogDashboardProfileSaved   = "[DASHBOARD] профиль сохранён user=%d name=%q"
)

// User-facing messages (recommendations / copy shown in the dashboard).
const (
	MsgDashboardUploadFirstAnalysis = "Загрузите первый анализ или пройдите биоскан, чтобы увидеть свой профиль."
	MsgDashboardWaterBalance        = "Поддерживайте водный баланс (≈2 л воды в день)."
	MsgDashboardRepeatAnalyses      = "Регулярно повторяйте анализы для отслеживания динамики."
	MsgDashboardActivityGrew        = "Активность выросла - отличный прогресс за месяц (индекс 60 → 82)."
	MsgDashboardControlHemoglobin   = "Контролируйте уровень гемоглобина раз в 3–4 недели."
	MsgDashboardUploadAnalyses      = "Регулярно загружайте анализы и биосканы, чтобы отслеживать динамику здоровья."
	MsgDashboardSpecifyGoal         = "Укажите цель в профиле, чтобы получать персональные рекомендации."
	MsgDashboardGoalTemplate        = "Ваша цель: %s. Зафиксируйте исходные показатели, затем повторяйте замеры раз в 2–4 недели."
	MsgDashboardIndicatorsLoaded    = "Показатели загружены из отчёта. Подробности - в PDF-документе."
)
